<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
      $countries = [
          ['name' => 'Afghanistan', 'iso' => 'AF', 'prefix' => '+93'],
          ['name' => 'Albania', 'iso' => 'AL', 'prefix' => '+355'],
          ['name' => 'Algeria', 'iso' => 'DZ', 'prefix' => '+213'],
          ['name' => 'Andorra', 'iso' => 'AD', 'prefix' => '+376'],
          ['name' => 'Angola', 'iso' => 'AO', 'prefix' => '+244'],
          ['name' => 'Antigua and Barbuda', 'iso' => 'AG', 'prefix' => '+1-268'],
          ['name' => 'Argentina', 'iso' => 'AR', 'prefix' => '+54'],
          ['name' => 'Armenia', 'iso' => 'AM', 'prefix' => '+374'],
          ['name' => 'Australia', 'iso' => 'AU', 'prefix' => '+61'],
          ['name' => 'Austria', 'iso' => 'AT', 'prefix' => '+43'],
          ['name' => 'Azerbaijan', 'iso' => 'AZ', 'prefix' => '+994'],
          ['name' => 'Bahamas', 'iso' => 'BS', 'prefix' => '+1-242'],
          ['name' => 'Bahrain', 'iso' => 'BH', 'prefix' => '+973'],
          ['name' => 'Bangladesh', 'iso' => 'BD', 'prefix' => '+880'],
          ['name' => 'Barbados', 'iso' => 'BB', 'prefix' => '+1-246'],
          ['name' => 'Belarus', 'iso' => 'BY', 'prefix' => '+375'],
          ['name' => 'Belgium', 'iso' => 'BE', 'prefix' => '+32'],
          ['name' => 'Belize', 'iso' => 'BZ', 'prefix' => '+501'],
          ['name' => 'Benin', 'iso' => 'BJ', 'prefix' => '+229'],
          ['name' => 'Bhutan', 'iso' => 'BT', 'prefix' => '+975'],
          ['name' => 'Bolivia', 'iso' => 'BO', 'prefix' => '+591'],
          ['name' => 'Bosnia and Herzegovina', 'iso' => 'BA', 'prefix' => '+387'],
          ['name' => 'Botswana', 'iso' => 'BW', 'prefix' => '+267'],
          ['name' => 'Brazil', 'iso' => 'BR', 'prefix' => '+55'],
          ['name' => 'Brunei', 'iso' => 'BN', 'prefix' => '+673'],
          ['name' => 'Bulgaria', 'iso' => 'BG', 'prefix' => '+359'],
          ['name' => 'Burkina Faso', 'iso' => 'BF', 'prefix' => '+226'],
          ['name' => 'Burundi', 'iso' => 'BI', 'prefix' => '+257'],
          ['name' => 'Cabo Verde', 'iso' => 'CV', 'prefix' => '+238'],
          ['name' => 'Cambodia', 'iso' => 'KH', 'prefix' => '+855'],
          ['name' => 'Cameroon', 'iso' => 'CM', 'prefix' => '+237'],
          ['name' => 'Canada', 'iso' => 'CA', 'prefix' => '+1'],
          ['name' => 'Central African Republic', 'iso' => 'CF', 'prefix' => '+236'],
          ['name' => 'Chad', 'iso' => 'TD', 'prefix' => '+235'],
          ['name' => 'Chile', 'iso' => 'CL', 'prefix' => '+56'],
          ['name' => 'China', 'iso' => 'CN', 'prefix' => '+86'],
          ['name' => 'Colombia', 'iso' => 'CO', 'prefix' => '+57'],
          ['name' => 'Comoros', 'iso' => 'KM', 'prefix' => '+269'],
          ['name' => 'Congo (Brazzaville)', 'iso' => 'CG', 'prefix' => '+242'],
          ['name' => 'Congo (Kinshasa)', 'iso' => 'CD', 'prefix' => '+243'],
          ['name' => 'Costa Rica', 'iso' => 'CR', 'prefix' => '+506'],
          ['name' => 'Croatia', 'iso' => 'HR', 'prefix' => '+385'],
          ['name' => 'Cuba', 'iso' => 'CU', 'prefix' => '+53'],
          ['name' => 'Cyprus', 'iso' => 'CY', 'prefix' => '+357'],
          ['name' => 'Czech Republic', 'iso' => 'CZ', 'prefix' => '+420'],
          ['name' => 'Denmark', 'iso' => 'DK', 'prefix' => '+45'],
          ['name' => 'Djibouti', 'iso' => 'DJ', 'prefix' => '+253'],
          ['name' => 'Dominica', 'iso' => 'DM', 'prefix' => '+1-767'],
          ['name' => 'Dominican Republic', 'iso' => 'DO', 'prefix' => '+1-809, +1-829, +1-849'],
          ['name' => 'Ecuador', 'iso' => 'EC', 'prefix' => '+593'],
          ['name' => 'Egypt', 'iso' => 'EG', 'prefix' => '+20'],
          ['name' => 'El Salvador', 'iso' => 'SV', 'prefix' => '+503'],
          ['name' => 'Equatorial Guinea', 'iso' => 'GQ', 'prefix' => '+240'],
          ['name' => 'Eritrea', 'iso' => 'ER', 'prefix' => '+291'],
          ['name' => 'Estonia', 'iso' => 'EE', 'prefix' => '+372'],
          ['name' => 'Eswatini', 'iso' => 'SZ', 'prefix' => '+268'],
          ['name' => 'Ethiopia', 'iso' => 'ET', 'prefix' => '+251'],
          ['name' => 'Fiji', 'iso' => 'FJ', 'prefix' => '+679'],
          ['name' => 'Finland', 'iso' => 'FI', 'prefix' => '+358'],
          ['name' => 'France', 'iso' => 'FR', 'prefix' => '+33'],
          ['name' => 'Gabon', 'iso' => 'GA', 'prefix' => '+241'],
          ['name' => 'Gambia', 'iso' => 'GM', 'prefix' => '+220'],
          ['name' => 'Georgia', 'iso' => 'GE', 'prefix' => '+995'],
          ['name' => 'Germany', 'iso' => 'DE', 'prefix' => '+49'],
          ['name' => 'Ghana', 'iso' => 'GH', 'prefix' => '+233'],
          ['name' => 'Greece', 'iso' => 'GR', 'prefix' => '+30'],
          ['name' => 'Grenada', 'iso' => 'GD', 'prefix' => '+1-473'],
          ['name' => 'Guatemala', 'iso' => 'GT', 'prefix' => '+502'],
          ['name' => 'Guinea', 'iso' => 'GN', 'prefix' => '+224'],
          ['name' => 'Guinea-Bissau', 'iso' => 'GW', 'prefix' => '+245'],
          ['name' => 'Guyana', 'iso' => 'GY', 'prefix' => '+592'],
          ['name' => 'Haiti', 'iso' => 'HT', 'prefix' => '+509'],
          ['name' => 'Honduras', 'iso' => 'HN', 'prefix' => '+504'],
          ['name' => 'Hungary', 'iso' => 'HU', 'prefix' => '+36'],
          ['name' => 'Iceland', 'iso' => 'IS', 'prefix' => '+354'],
          ['name' => 'India', 'iso' => 'IN', 'prefix' => '+91'],
          ['name' => 'Indonesia', 'iso' => 'ID', 'prefix' => '+62'],
          ['name' => 'Iraq', 'iso' => 'IQ', 'prefix' => '+964'],
          ['name' => 'Ireland', 'iso' => 'IE', 'prefix' => '+353'],
          ['name' => 'Israel', 'iso' => 'IL', 'prefix' => '+972'],
          ['name' => 'Italy', 'iso' => 'IT', 'prefix' => '+39'],
          ['name' => 'Jamaica', 'iso' => 'JM', 'prefix' => '+1-876'],
          ['name' => 'Japan', 'iso' => 'JP', 'prefix' => '+81'],
          ['name' => 'Jordan', 'iso' => 'JO', 'prefix' => '+962'],
          ['name' => 'Kazakhstan', 'iso' => 'KZ', 'prefix' => '+7'],
          ['name' => 'Kenya', 'iso' => 'KE', 'prefix' => '+254'],
          ['name' => 'Kiribati', 'iso' => 'KI', 'prefix' => '+686'],
          ['name' => 'Kuwait', 'iso' => 'KW', 'prefix' => '+965'],
          ['name' => 'Kyrgyzstan', 'iso' => 'KG', 'prefix' => '+996'],
          ['name' => 'Laos', 'iso' => 'LA', 'prefix' => '+856'],
          ['name' => 'Latvia', 'iso' => 'LV', 'prefix' => '+371'],
          ['name' => 'Lebanon', 'iso' => 'LB', 'prefix' => '+961'],
          ['name' => 'Lesotho', 'iso' => 'LS', 'prefix' => '+266'],
          ['name' => 'Liberia', 'iso' => 'LR', 'prefix' => '+231'],
          ['name' => 'Libya', 'iso' => 'LY', 'prefix' => '+218'],
          ['name' => 'Liechtenstein', 'iso' => 'LI', 'prefix' => '+423'],
          ['name' => 'Lithuania', 'iso' => 'LT', 'prefix' => '+370'],
          ['name' => 'Luxembourg', 'iso' => 'LU', 'prefix' => '+352'],
          ['name' => 'Madagascar', 'iso' => 'MG', 'prefix' => '+261'],
          ['name' => 'Malawi', 'iso' => 'MW', 'prefix' => '+265'],
          ['name' => 'Malaysia', 'iso' => 'MY', 'prefix' => '+60'],
          ['name' => 'Maldives', 'iso' => 'MV', 'prefix' => '+960'],
          ['name' => 'Mali', 'iso' => 'ML', 'prefix' => '+223'],
          ['name' => 'Malta', 'iso' => 'MT', 'prefix' => '+356'],
          ['name' => 'Marshall Islands', 'iso' => 'MH', 'prefix' => '+692'],
          ['name' => 'Mauritania', 'iso' => 'MR', 'prefix' => '+222'],
          ['name' => 'Mauritius', 'iso' => 'MU', 'prefix' => '+230'],
          ['name' => 'Mexico', 'iso' => 'MX', 'prefix' => '+52'],
          ['name' => 'Micronesia', 'iso' => 'FM', 'prefix' => '+691'],
          ['name' => 'Moldova', 'iso' => 'MD', 'prefix' => '+373'],
          ['name' => 'Monaco', 'iso' => 'MC', 'prefix' => '+377'],
          ['name' => 'Mongolia', 'iso' => 'MN', 'prefix' => '+976'],
          ['name' => 'Montenegro', 'iso' => 'ME', 'prefix' => '+382'],
          ['name' => 'Morocco', 'iso' => 'MA', 'prefix' => '+212'],
          ['name' => 'Mozambique', 'iso' => 'MZ', 'prefix' => '+258'],
          ['name' => 'Myanmar', 'iso' => 'MM', 'prefix' => '+95'],
          ['name' => 'Namibia', 'iso' => 'NA', 'prefix' => '+264'],
          ['name' => 'Nauru', 'iso' => 'NR', 'prefix' => '+674'],
          ['name' => 'Nepal', 'iso' => 'NP', 'prefix' => '+977'],
          ['name' => 'Netherlands', 'iso' => 'NL', 'prefix' => '+31'],
          ['name' => 'New Zealand', 'iso' => 'NZ', 'prefix' => '+64'],
          ['name' => 'Nicaragua', 'iso' => 'NI', 'prefix' => '+505'],
          ['name' => 'Niger', 'iso' => 'NE', 'prefix' => '+227'],
          ['name' => 'Nigeria', 'iso' => 'NG', 'prefix' => '+234'],
          ['name' => 'North Macedonia', 'iso' => 'MK', 'prefix' => '+389'],
          ['name' => 'Norway', 'iso' => 'NO', 'prefix' => '+47'],
          ['name' => 'Oman', 'iso' => 'OM', 'prefix' => '+968'],
          ['name' => 'Pakistan', 'iso' => 'PK', 'prefix' => '+92'],
          ['name' => 'Palau', 'iso' => 'PW', 'prefix' => '+680'],
          ['name' => 'Palestine', 'iso' => 'PS', 'prefix' => '+970'],
          ['name' => 'Panama', 'iso' => 'PA', 'prefix' => '+507'],
          ['name' => 'Papua New Guinea', 'iso' => 'PG', 'prefix' => '+675'],
          ['name' => 'Paraguay', 'iso' => 'PY', 'prefix' => '+595'],
          ['name' => 'Peru', 'iso' => 'PE', 'prefix' => '+51'],
          ['name' => 'Philippines', 'iso' => 'PH', 'prefix' => '+63'],
          ['name' => 'Poland', 'iso' => 'PL', 'prefix' => '+48'],
          ['name' => 'Portugal', 'iso' => 'PT', 'prefix' => '+351'],
          ['name' => 'Qatar', 'iso' => 'QA', 'prefix' => '+974'],
          ['name' => 'Romania', 'iso' => 'RO', 'prefix' => '+40'],
          ['name' => 'Russia', 'iso' => 'RU', 'prefix' => '+7'],
          ['name' => 'Rwanda', 'iso' => 'RW', 'prefix' => '+250'],
          ['name' => 'Saint Kitts and Nevis', 'iso' => 'KN', 'prefix' => '+1-869'],
          ['name' => 'Saint Lucia', 'iso' => 'LC', 'prefix' => '+1-758'],
          ['name' => 'Saint Vincent and the Grenadines', 'iso' => 'VC', 'prefix' => '+1-784'],
          ['name' => 'Samoa', 'iso' => 'WS', 'prefix' => '+685'],
          ['name' => 'San Marino', 'iso' => 'SM', 'prefix' => '+378'],
          ['name' => 'Sao Tome and Principe', 'iso' => 'ST', 'prefix' => '+239'],
          ['name' => 'Saudi Arabia', 'iso' => 'SA', 'prefix' => '+966'],
          ['name' => 'Senegal', 'iso' => 'SN', 'prefix' => '+221'],
          ['name' => 'Serbia', 'iso' => 'RS', 'prefix' => '+381'],
          ['name' => 'Seychelles', 'iso' => 'SC', 'prefix' => '+248'],
          ['name' => 'Sierra Leone', 'iso' => 'SL', 'prefix' => '+232'],
          ['name' => 'Singapore', 'iso' => 'SG', 'prefix' => '+65'],
          ['name' => 'Slovakia', 'iso' => 'SK', 'prefix' => '+421'],
          ['name' => 'Slovenia', 'iso' => 'SI', 'prefix' => '+386'],
          ['name' => 'Solomon Islands', 'iso' => 'SB', 'prefix' => '+677'],
          ['name' => 'Somalia', 'iso' => 'SO', 'prefix' => '+252'],
          ['name' => 'South Africa', 'iso' => 'ZA', 'prefix' => '+27'],
          ['name' => 'South Korea', 'iso' => 'KR', 'prefix' => '+82'],
          ['name' => 'South Sudan', 'iso' => 'SS', 'prefix' => '+211'],
          ['name' => 'Spain', 'iso' => 'ES', 'prefix' => '+34'],
          ['name' => 'Sri Lanka', 'iso' => 'LK', 'prefix' => '+94'],
          ['name' => 'Sudan', 'iso' => 'SD', 'prefix' => '+249'],
          ['name' => 'Suriname', 'iso' => 'SR', 'prefix' => '+597'],
          ['name' => 'Sweden', 'iso' => 'SE', 'prefix' => '+46'],
          ['name' => 'Switzerland', 'iso' => 'CH', 'prefix' => '+41'],
          ['name' => 'Taiwan', 'iso' => 'TW', 'prefix' => '+886'],
          ['name' => 'Tajikistan', 'iso' => 'TJ', 'prefix' => '+992'],
          ['name' => 'Tanzania', 'iso' => 'TZ', 'prefix' => '+255'],
          ['name' => 'Thailand', 'iso' => 'TH', 'prefix' => '+66'],
          ['name' => 'Timor-Leste', 'iso' => 'TL', 'prefix' => '+670'],
          ['name' => 'Togo', 'iso' => 'TG', 'prefix' => '+228'],
          ['name' => 'Tonga', 'iso' => 'TO', 'prefix' => '+676'],
          ['name' => 'Trinidad and Tobago', 'iso' => 'TT', 'prefix' => '+1-868'],
          ['name' => 'Tunisia', 'iso' => 'TN', 'prefix' => '+216'],
          ['name' => 'Turkey', 'iso' => 'TR', 'prefix' => '+90'],
          ['name' => 'Turkmenistan', 'iso' => 'TM', 'prefix' => '+993'],
          ['name' => 'Tuvalu', 'iso' => 'TV', 'prefix' => '+688'],
          ['name' => 'Uganda', 'iso' => 'UG', 'prefix' => '+256'],
          ['name' => 'Ukraine', 'iso' => 'UA', 'prefix' => '+380'],
          ['name' => 'United Arab Emirates', 'iso' => 'AE', 'prefix' => '+971'],
          ['name' => 'United Kingdom', 'iso' => 'GB', 'prefix' => '+44'],
          ['name' => 'United States', 'iso' => 'US', 'prefix' => '+1'],
          ['name' => 'Uruguay', 'iso' => 'UY', 'prefix' => '+598'],
          ['name' => 'Uzbekistan', 'iso' => 'UZ', 'prefix' => '+998'],
          ['name' => 'Vanuatu', 'iso' => 'VU', 'prefix' => '+678'],
          ['name' => 'Vatican City', 'iso' => 'VA', 'prefix' => '+379'],
          ['name' => 'Venezuela', 'iso' => 'VE', 'prefix' => '+58'],
          ['name' => 'Vietnam', 'iso' => 'VN', 'prefix' => '+84'],
          ['name' => 'Yemen', 'iso' => 'YE', 'prefix' => '+967'],
          ['name' => 'Zambia', 'iso' => 'ZM', 'prefix' => '+260'],
          ['name' => 'Zimbabwe', 'iso' => 'ZW', 'prefix' => '+263']
      ];

      foreach ($countries as $country) Country::create($country);
    }
}
