<div>
  <div class="py-6 mb-4 border-y-1 border-gray/30">
    {{-- HEADER --}}
    <div class="text-2xl font-semibold mb-4">Two-Factor Authentication (2FA)</div>
    
    {{-- DESCRIPTION --}}
    <div class="">
      <p>Secure your account with Two-Factor Authentication (2FA).</p>
      <p>1. Scan the QR code below using an authenticator app (like Google Authenticator or Authy).</p>
      <p>2. Then, enter the verification code generated by the app in the field below.</p>
    </div>
  </div>

  <div class="text-center mb-4">
    <div class="mb-3">
      <img class="max-w-full inline-block" src="{{ asset('assets/img/qr.png') }}" alt="QR">
    </div>
    <div class="text-gray mb-1">
      Setup Key (for manual entry)
    </div>
    <div class="mb-2">DREDTFYUIOPLTL;’KLLRDTEYDTUYIYUIJOKPL[LOIUYGT</div>
    <div class="">
      Save this Backup Reset Code in a safe place.<br>
      You will need it to recover your account if you lose access to your authenticator app.
    </div>

  </div>

  <div class="flex flex-col gap-3 pb-6 mb-4 border-y-1 border-gray/30">
    <div class="">
      <div class="text-gray mb-1">Backup Reset Code</div>
      <div class="bg-light relative px-3 py-3 !pr-9 rounded flex justify-between items-center hover:cursor-pointer copyToClipboard" data-target="referal">
        <input type="hidden" value="DREDTFYUIOPLTL;’KLLRDTEYDTUYIYUIJOKPL[LOIUYGT" data-copyId="referal" readonly />
        <div class="break-all">
          DREDTFYUIOPLTL;’KLLRDTEYDTUYIYUIJOKPL[LOIUYGT
        </div>
        <div class="">
          <img src="{{ asset('assets/img/copy-icon.svg') }}" alt="Copy">
        </div>
        <x-tooltip message="tooltip" class="right-3"></x-tooltip>
      </div>
    </div>

    <x-form.input label="Verification Code" placeholder="Enter Code" data-input="integer" />

    <x-form.checkbox label="I have saved my Backup Reset Code"></x-form.checkbox>
  </div>

  {{-- BUTTONS --}}
  <div class="flex justify-center items-center gap-3">
    <x-btn class="!text-sm sm:!text-base !w-auto sm:!px-12" wire:click.prevent="$dispatch('closeModal')" outlined>Cancel</x-btn>
    <x-btn class="!text-sm sm:!text-base !grow">Enable 2FA</x-btn>
  </div>

</div>
